webapp/rutracker/views.py
from flask import Blueprint, render_template
from flask_login import login_required
from webapp.rutracker.models import Torrent4
from webapp.rutracker.forms import RutrackerPage, RutrackerSearch
from webapp.get_rutracker_page import get_html, parse_torrent_page, parse_search_result, get_rutracker_session, search_in_db
from webapp.config import RUTRACKER_LOGIN, RUTRACKER_LOGIN_URL, RUTRACKER_PASSWORD, RUTRACKER_SEARCH_URL

blueprint = Blueprint('rutracker', __name__)

rutracker_session = get_rutracker_session(RUTRACKER_LOGIN_URL, RUTRACKER_LOGIN, RUTRACKER_PASSWORD)


@blueprint.route('/', methods=['POST', 'GET'])
@login_required
def index():
    page_title = "Hevarie - parser"
    rutracker_form = RutrackerPage()
    rutracker_search = RutrackerSearch()
    return render_template(
        'rutracker/main_page.html', page_title=page_title, rutracker_form=rutracker_form, rutracker_search=rutracker_search, sess=rutracker_session
    )


@blueprint.route('/search_result', methods=['POST', 'GET'])
def search_rutracker_page():
    form = RutrackerSearch()
    page_title = "Результат поиска на Rutracker"
    search_text = "%".join(form.search_text.data.split())
    search_result = search_in_db(search_text)
    if not search_result:
        parse_search_result(get_html(f'{RUTRACKER_SEARCH_URL}{search_text}', rutracker_session), rutracker_session)
        search_result = Torrent4.query.filter(Torrent4.torrent_name.ilike(f'%{search_text}%')).all()
    if search_result:
        return render_template(
                'rutracker/three_result.html', search_result=search_result[0:5], page_title=page_title, rutracker_search_url=f'{RUTRACKER_SEARCH_URL}{search_text}'
            )
    else:
        return ("Не найдено")


@blueprint.route('/rutracker_page/', methods=['POST', 'GET'])
def parsed_torrent_page():
    torrent_url = "https://rutracker.org/forum/viewtopic.php?t=5855263"
    page_title = "Rutracker Torrent"
    rutracker_page = parse_torrent_page(get_html(torrent_url, rutracker_session))
    if rutracker_page:
        return render_template(
            'rutracker/index.html', page_title=page_title,
            rutracker_page=rutracker_page
            )
    else:
        return("Rutracker page not found")

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import Tuser as User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('rutracker.index'))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно вошли на сайт Hevarie')
            return redirect(url_for('rutracker.index'))
    flash('Неправильное имя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно вышли')
    return redirect(url_for('user.login'))


@blueprint.route('/registration')
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('rutracker.index'))
    title = "Регистрация"
    registration_form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=registration_form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password1.data)
        db.session.add(new_user)
        db.session.commit()
        flash(f'Пользователь {new_user.username} успешно зарегистрирован')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле {getattr(form, field).label.text}: {error}')
        return redirect(url_for('user.registration'))

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
      {% include 'menu.html' %}
      <h1>{{ page_title }}</h1>
      {% block content %}{% endblock %}
    </div>         
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
      <div class="container-fluid">
        <h1>{{ page_title }}</h1>      
            <h2>
                  <a href="{{ rutracker_page }}" class="btn btn-primary btn-lg btn-block active" role="button" aria-pressed="true">Главная ссылка</a>   
            </h2>
        <div class="row">
          <div class="col">
              <h1>{{ rutracker_page.torrent_title }}</h1>

          </div>
        </div>
      </div> 

             
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/main_page.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
      <h1>{{ page_title }}</h1>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="alert alert-warning" role="alert">
          {% for message in messages %}
              {{ message }}<br>
          {% endfor %}
      </div>
      {% endif %}
      {% endwith %}
      <h2>{{ sess }}</h2>
        <div class="row">       
          <div class="col-8">
            <form action="{{ url_for('rutracker.parsed_torrent_page') }}" method="POST">
              <div class="form-group">
                 {{ rutracker_form.hidden_tag() }}
                 {{ rutracker_form.submit() }} 
            </div>
            </form>
          </div>
        </div>
        <div class="row-1">
            <div class="col-0">
                <form action="{{ url_for('rutracker.search_rutracker_page') }}" method="POST">
                  <div class="form-group">
                    {{ rutracker_search.hidden_tag() }}
                    {{ rutracker_search.search_text() }}
                    {{ rutracker_search.submit() }}
                  </div>
                </form>
            </div>
        </div>
    </div>

             
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Hevarie-torrent-parser</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Главная страница <span class="sr-only">(current)</span></a>
        </li>
      

      </ul>
      <ui class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" >{{ current_user.username }}. </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.logout') }}">Выход</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">Авторизация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.registration') }}">Регистрация</a>
        </li>
        {% endif %}
        </li>
      </ui>
    </div>
  </nav>